# Generated by Django 4.0.1 on 2022-01-16 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='caller',
        ),
    ]
