# Generated by Django 4.0.1 on 2022-01-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.IntegerField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.IntegerField(default='', max_length=70),
        ),
        migrations.AlterField(
            model_name='order',
            name='zip',
            field=models.IntegerField(default='', max_length=500),
        ),
    ]
